### PR TITLE
style more like unraid cpu stats

### PR DESCRIPTION
**Pull request by mlapaglia**
i need help creating the pkg file and getting the package filename, dates updated before this can be merged in

### CODE REVIEW

**Comment by b3rs3rk** [comment]
@mlapaglia Can you exclude the pkg files (md5 and txz) as well as any changes you made to the main plg file in this PR?  This will be a lot cleaner merge than having commits for when you ran the bash script to create the files.  Unless the new pkg is fully working/functional and intended to be the next available pkg I can't merge it as is or Community Apps will see a new version and start pushing it to everyone.

**Comment by mlapaglia** [comment]
do you make another PR with the new pkg or something? this is why i said i needed help :)

**Comment by b3rs3rk** [comment]
image

Based on the change comparison from my master branch to your PR branch, the screenshot shows the 4 files I need to implement your changes.  I will worry about the package creation and updating the plugin to community apps.  If you want these changes to be attributed to you, you need to be the one committing them.  Looking at your commit history, it looks like you find/replaced my name a bunch of times and then changed them back and committed them again.  Your work tree is pretty dirty in that respect.

It sounds like you aren't very comfortable with Git in general.  If I were you, I would save the 4 files you modified outside of your work tree.  Then you need to revert your fork to match my HEAD something similar to [this](https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream).  An even easier way, would be to first copy the 4 code files you changed out, then delete the entire fork from your local filesystem and your Github account.  Then re-fork, clone your fork locally, create a new branch instead of modifying master (say like dev-mlapaglia-ui), copy the 4 files back into the new branch, git add, git commit, git push and then re-open the PR from the new branch.

If you don't care about attribution (I'll still list you as a contributor in the README) I can just merge the 4 files that were changed after reviewing.  In other words, I can simply pull those 4 files, merge them locally and push to my repo and then create the package... but all your attribution would be lost.

Let me know.

**Comment by mlapaglia** [comment]
i replaced your name with mine so i could install it in my unraid for testing. i'll open up a new one

**Pull request closed without merging**
