### PR TITLE
Add new dashboard Layout for 6.12

### PR DESCRIPTION
**Pull request by SimonFair**
Add support for both Intel iGPU and DG2.

### CODE REVIEW

**Comment by SimonFair** [comment]
image
image
image
image

Note these panels can be moved between columns.

**Comment by SimonFair** [comment]
For intel devices show real model.

image
image

**Comment by b3rs3rk** [comment]
@SimonFair wow, lots of changes here but a quick skim shows it looks good.  Did you test on <= 6.11 to ensure there is no breakage?  I'm going to test it myself before I merge obviously but it looks great so far.

**Comment by SimonFair** [comment]
Only loaded on 6.10.3 to confirm panels look ok. I did create pkg on my repo if you want to use it.

**Comment by b3rs3rk** [comment]
I'll probably just drop the branch files over mine.  Worse comes to worse I can just reboot and it will go back to normal.

**Comment by SimonFair** [comment]
Just for info I have started on working on MultiGPU support but will raise as another PR. But will be a few weeks before it is ready

image

**Comment by SimonFair** [comment]
Added multigpu now so closing this one.

**Pull request closed without merging**
